[tool.black]
line-length = 88
target-version = ['py36']

[tool.pytest.ini_options]
tmp_path_retention_policy = "none"
markers = [
    "integration: integration tests",
    "unit: unit tests",
    "custom: custom integration tests",
    "smoke: smoke tests"
]
