__all__ = [
    "ONNX_FRAMEWORK",
    "KERAS_FRAMEWORK",
    "PYTORCH_FRAMEWORK",
    "TENSORFLOW_FRAMEWORK",
]


ONNX_FRAMEWORK = "onnx"
KERAS_FRAMEWORK = "keras"
PYTORCH_FRAMEWORK = "pytorch"
TENSORFLOW_FRAMEWORK = "tensorflow"
