version: 1.1.0

modifiers:
    - !GMPruningModifier
        end_epoch: 36.0
        final_sparsity: 0.03
        global_sparsity: False
        init_sparsity: 0.25
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: 
            - blocks.0.attn.qkv.weight
            - blocks.0.attn.proj.weight
            - blocks.0.mlp.fc1.weight
            - blocks.0.mlp.fc2.weight
            - blocks.1.attn.qkv.weight
            - blocks.1.attn.proj.weight
            - blocks.1.mlp.fc1.weight
            - blocks.1.mlp.fc2.weight
            - blocks.2.attn.qkv.weight
            - blocks.2.attn.proj.weight
            - blocks.2.mlp.fc1.weight
            - blocks.2.mlp.fc2.weight
            - blocks.3.attn.qkv.weight
            - blocks.3.attn.proj.weight
            - blocks.3.mlp.fc1.weight
            - blocks.3.mlp.fc2.weight
            - blocks.4.attn.qkv.weight
            - blocks.4.attn.proj.weight
            - blocks.4.mlp.fc1.weight
            - blocks.4.mlp.fc2.weight
            - blocks.5.attn.qkv.weight
            - blocks.5.attn.proj.weight
            - blocks.5.mlp.fc1.weight
            - blocks.5.mlp.fc2.weight
            - blocks.6.attn.qkv.weight
            - blocks.6.attn.proj.weight
            - blocks.6.mlp.fc1.weight
            - blocks.6.mlp.fc2.weight
            - blocks.7.attn.qkv.weight
            - blocks.7.attn.proj.weight
            - blocks.7.mlp.fc1.weight
            - blocks.7.mlp.fc2.weight
            - blocks.8.attn.qkv.weight
            - blocks.8.attn.proj.weight
            - blocks.8.mlp.fc1.weight
            - blocks.8.mlp.fc2.weight
            - blocks.9.attn.qkv.weight
            - blocks.9.attn.proj.weight
            - blocks.9.mlp.fc1.weight
            - blocks.9.mlp.fc2.weight
            - blocks.10.attn.qkv.weight
            - blocks.10.attn.proj.weight
            - blocks.10.mlp.fc1.weight
            - blocks.10.mlp.fc2.weight
            - blocks.11.attn.qkv.weight
            - blocks.11.attn.proj.weight
            - blocks.11.mlp.fc1.weight
            - blocks.11.mlp.fc2.weight
        phased: False
        score_type: magnitude
        start_epoch: 1.0
        update_frequency: 0.5

    - !EpochRangeModifier
        end_epoch: 100.0
        start_epoch: 0.0

    - !SetLearningRateModifier
        constant_logging: False
        end_epoch: -1
        learning_rate: 0.002505
        start_epoch: 0.0

    - !LearningRateModifier
        constant_logging: False
        end_epoch: -1.0
        init_lr: 0.00062625
        lr_class: StepLR
        lr_kwargs: {'step_size': 10, 'gamma': 0.25}
        start_epoch: 40.0
        update_frequency: -1.0
