version: 1.1.0

modifiers:
    - !EpochRangeModifier
        end_epoch: 6.0
        start_epoch: 0.0

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.97
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_20/kernel:0', 'conv2d_18/kernel:0', 'conv2d_19/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.75
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_16/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.95
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_15/kernel:0', 'conv2d_17/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.94
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_13/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.92
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_14/kernel:0', 'conv2d_10/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.93
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_11/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.61
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_9/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.89
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_12/kernel:0', 'conv2d_8/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.87
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_6/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.83
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_7/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.84
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_4/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.82
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_5/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.81
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_2/kernel:0', 'conv2d_3/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.41
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !GMPruningModifier
        end_epoch: 4.0
        final_sparsity: 0.8
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        params: ['conv2d_1/kernel:0']
        start_epoch: 1.0
        update_frequency: 0.075

    - !SetLearningRateModifier
        end_epoch: -1
        learning_rate: 0.00055
        log_types: __ALL__
        start_epoch: 0.0

    - !LearningRateModifier
        end_epoch: -1.0
        init_lr: 0.0001375
        log_types: __ALL__
        lr_class: StepLR
        lr_kwargs: {'step_size': 1.0, 'gamma': 0.25}
        start_epoch: 2.0
        update_frequency: -1
