compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
enable_cpu_affinity: false
gpu_ids: 0
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false