version: 1.1.0

modifiers:
    - !ACDCPruningModifier
        compression_sparsity: 0.9
        end_epoch: 3
        leave_enabled: True
        log_types: __ALL__
        mask_type: unstructured
        momentum_buffer_reset: True
        params: ['re:.*conv*', 're:.*fc.weight*']
        start_epoch: 0
        update_frequency: 1

    - !EpochRangeModifier
        end_epoch: 3
        start_epoch: 0

metadata: {'sample': 'metadata', 'yo': 3}