version: 1.1.0
modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 240.0

  - !GlobalMagnitudePruningModifier
    params: __ALL_PRUNABLE__
    init_sparsity: 0.25
    final_sparsity: 0.90
    update_frequency: 2.0
    start_epoch: 3.0
    end_epoch: 65.0

  - !LearningRateFunctionModifier
    start_epoch: 0
    end_epoch: 3
    lr_func: linear
    init_lr: 0
    final_lr: 0.01
    param_groups: [0, 1]

  - !LearningRateFunctionModifier
    start_epoch: 0
    end_epoch: 3
    lr_func: linear
    init_lr: 0.1
    final_lr: 0.01
    param_groups: [2]

