version: 1.1.0

__metadata__:

modifiers:
    - !GMPruningModifier
        end_epoch: 10.0
        final_sparsity: 0.1
        global_sparsity: False
        init_sparsity: 0.05
        inter_func: cubic
        leave_enabled: True
        mask_type: unstructured
        params: ['model.0.conv.weight', 'model.1.conv.weight']
        start_epoch: 5.0
        update_frequency: 1.0

    - !EpochRangeModifier
        end_epoch: 15.0
        start_epoch: 0.0

    - !QuantizationModifier
        disable_quantization_observer_epoch: 13.0
        end_epoch: -1.0
        freeze_bn_stats_epoch: 12.0
        ignore: ['Upsample', 'Concat', 'SiLU']
        model_fuse_fn_kwargs: {'inplace': True}
        scheme: {'input_activations': {'num_bits': 8, 'symmetric': False, 'kwargs': {}}, 'weights': {'num_bits': 8, 'symmetric': True, 'kwargs': {}}, 'output_activations': 'null', 'target_hardware': 'null'}
        scheme_overrides: {}
        start_epoch: 11.0
        strict: True
