name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Fetch active from .MAINTAINERS
        id: reviewers
        run: >-
          echo "::set-output name=REVIEWERS::$(
            grep -v '^#' .MAINTAINERS |
            paste -s -d, -
          )"
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}  # assign PR author to PR
          reviewers: ${{ steps.reviewers.outputs.REVIEWERS }}
          max-num-of-reviewers: 1  # randomly selects 1 reviewer
          ready-comment: '<reviewers> assigned for review'
          draft-keyword: wip  # will not assign reviewers until WIP removed from title
