name: Build Wheel and Push to s3
on:
  workflow_call:
    inputs:
      build-label:
        description: "requested runner label"
        type: string
        required: true
      dev:
        type: string
        required: true 
      release:
        type: string
        required: true
      name:
        type: string
      filename:
        type: string
        required: true
      bucket_name:
        type: string
        required: true
      python:
        type: string
    outputs:
      wheel:
        value: ${{ jobs.build-wheel-and-push.outputs.wheel }}

jobs:
  build-wheel-and-push:
    runs-on: ${{ inputs.build-label }}
    outputs:
      wheel: ${{ steps.push-wheel.outputs.wheel }}
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to s3
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_WEBIDENTITY_FOR_GITHUB_ACTIONS }}
        aws-region: us-east-1 
    
    - name: Set Env
      run: |
        pip3 install virtualenv
        virtualenv venv
        source venv/bin/activate

    - name: Build PyPi Wheel
      id: build-wheel
      uses: neuralmagic/nm-actions/actions/pypi_build@main
      with:
        dev: ${{ inputs.dev }}
        release: ${{ inputs.release }}
        name: ${{ inputs.name }}
    
    - name: Push to s3 bucket
      id: push-wheel
      uses: neuralmagic/nm-actions/actions/s3_push@main
      with:
        filename: ${{ inputs.filename }}
        bucket_name: ${{ inputs.bucket_name }}