name: Build and Publish

on:
  push:
    tags:
      - '*'
    branches:
      - 'release/*'
      - 'test-image-push/*'

jobs:
  build-and-push-docker-image:
    name: Build and Push Version Tagged Docker Images to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Current branch name
        if: steps.branch-name.outputs.is_tag == 'true'
        run: |
          echo "${{ steps.branch-name.outputs.tag }}"

      - name: Build and  push sparseml/sparseml-all
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=all
            VERSION=${{ steps.branch-name.outputs.tag }}
          tags: |
            ghcr.io/neuralmagic/sparseml-all:${{ steps.branch-name.outputs.tag }}
            ghcr.io/neuralmagic/sparseml:${{ steps.branch-name.outputs.tag }}

      - name: Build and push sparseml-torchvision
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=torchvision
            VERSION=${{ steps.branch-name.outputs.tag }}
          tags: |
            ghcr.io/neuralmagic/sparseml-torchvision:${{ steps.branch-name.outputs.tag }}
            

      - name: Build and push sparseml-transformers
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=transformers
            VERSION=${{ steps.branch-name.outputs.tag }}
          tags: |
            ghcr.io/neuralmagic/sparseml-transformers:${{ steps.branch-name.outputs.tag }}            

      - name: Build and push sparseml-ultralytics
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=ultralytics
            VERSION=${{ steps.branch-name.outputs.tag }}
          tags: |
            ghcr.io/neuralmagic/sparseml-torchvision:${{ steps.branch-name.outputs.tag }}
            

      - name: Build and push sparseml-yolov5
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=yolov5
            VERSION=${{ steps.branch-name.outputs.tag }}
          tags: |
            ghcr.io/neuralmagic/sparseml-yolov5:${{ steps.branch-name.outputs.tag }}

      - name: Build and push sparseml-base
        if: steps.branch-name.outputs.is_tag == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=base
            VERSION=${{ steps.branch-name.outputs.tag }}
          tags: |
            ghcr.io/neuralmagic/sparseml-base:${{ steps.branch-name.outputs.tag }}
            

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
