name: Build and Publish

on:
  push:
    tags:
      - '*'
    branches:
      - 'release/*'
      - 'docker-infra-test'

jobs:
  build-and-push-docker-image:
    name: Build and Push Version Tagged Docker Images to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract-version

      - name: Build and  push sparseml/sparseml-all
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=all
            VERSION=${{ steps.extract-version.outputs.version }}
          push: true
          tags: |
            ghcr.io/neuralmagic/sparseml-all:${{ steps.extract-version.outputs.version }}
#            ghcr.io/neuralmagic/sparseml:${{ steps.extract-version.outputs.version }}

      - name: Build and push sparseml-torchvision
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=torchvision
            VERSION=${{ steps.extract-version.outputs.version }}
          push: true
          tags: |
            ghcr.io/neuralmagic/sparseml-torchvision:${{ steps.extract-version.outputs.version }}
            

      - name: Build and push sparseml-transformers
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          build-args: |
            DEPS=transformers
            VERSION=${{ steps.extract-version.outputs.version }}
          tags: |
            ghcr.io/neuralmagic/sparseml-transformers:${{ steps.extract-version.outputs.version }}            

      - name: Build and push sparseml-ultralytics
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          build-args: |
            DEPS=ultralytics
            VERSION=${{ steps.extract-version.outputs.version }}
          tags: |
            ghcr.io/neuralmagic/sparseml-torchvision:${{ steps.extract-version.outputs.version }}
            

      - name: Build and push sparseml-yolov5
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          build-args: |
            DEPS=yolov5
            VERSION=${{ steps.extract-version.outputs.version }}
          tags: |
            ghcr.io/neuralmagic/sparseml-yolov5:${{ steps.extract-version.outputs.version }}

      - name: Build and push sparseml-base
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          build-args: |
            DEPS=base
            VERSION=${{ steps.extract-version.outputs.version }}
          tags: |
            ghcr.io/neuralmagic/sparseml-base:${{ steps.extract-version.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
