name: build-release
run-name: ${{ github.workflow }} is to create release wheel file for pypi
on:
  push:
    branches:
      - 'release/[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:

    BUILD-SPARSEML-RELEASE:

      uses: ./.github/workflows/util.yml
      with:
        runs_on: ubuntu-22.04
        run_id: ${{ github.run_id }}
        build_type: release
        testmo_project_id: 9
      secrets: inherit
