name: Build PyPi Wheel and Docker Container
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push: 
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  id-token: write
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# TODO: do we want to push to nightly everytime we push to main?
# if not dev or release, will create a nightly build; turning off release for not
env:
  RELEASE: 'false'
  # DEV: ${{ github.base_ref == 'main' && github.event_name == 'pull_request'}}
  DEV: 'false'
  NIGHTLY: ${{ DEV == 'false' && RELEASE == 'false'}}
jobs:
  set-outputs:
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.set-outputs.outputs.dev }}
      release: ${{ steps.set-outputs.outputs.release }}
    steps:
      - name: Set variables for workflows
        id: set-outputs
        run: |
          echo "dev=$DEV" >> $GITHUB_OUTPUT
          echo "release=$RELEASE" >> $GITHUB_OUTPUT
          echo "nightly=$NIGHTLY" >> $GITHUB_OUTPUT

  test-nightly:
    needs: set-outputs
    if: ${{ needs.set-outputs.outputs.nightly  == 'true'}}
    uses: ./.github/workflows/test-nightly.yml

  build-wheel-and-push:
    needs: [set-outputs, test-nightly]
    uses: ./.github/workflows/build-wheel.yml
    with:
      build-label: ubuntu-20.04
      dev: ${{ needs.set-outputs.outputs.dev }}
      release: ${{ needs.set-outputs.outputs.release  }}
      name: ${{ github.event.number }} 
      filename: dist/*.whl
      bucket_name: nm-actions-test
      python: '3.10'
    secrets: inherit

  test-wheel-and-publish:
    needs: [set-outputs, build-wheel-and-push]
    uses: ./.github/workflows/test-wheel-and-publish.yml
    with:
      build-label: ubuntu-20.04
      whl: ${{ needs.build-wheel-and-push.outputs.wheel }}
      python: '3.10'
      dev: ${{ needs.set-outputs.outputs.dev }}
      release: ${{ needs.set-outputs.outputs.release  }}
    secrets: inherit

  # TODO: add release container build steps once 
  build-container-and-push:
    needs: [test-wheel-and-publish, set-outputs]
    uses: ./.github/workflows/build-container.yml
    with:
      build-label: k8s-eng-gpu-16G-t4-32G
      dev: ${{ needs.set-outputs.outputs.dev }}
      release: ${{ needs.set-outputs.outputs.release  }}
      name: ${{ github.event.number }}
    secrets: inherit