name: 'coverage'
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Report Coverage 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}