name: Run Nightly Tests
on:
  push:
    branches:
      - '*'
jobs:
  test-nightly-tests:
    runs-on: k8s-mle-gpu-38-vcpu-168GB-ram-2-v100-32G
    env:
      CADENCE: "nightly"
      SPARSEZOO_TEST_MODE: "true"
      CLEARML_WEB_HOST: ${{ secrets.CLEARML_WEB_HOST }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_FILES_HOST:  ${{ secrets.CLEARML_FILES_HOST }}
      CLEARML_API_SECRET_KEY:  ${{ secrets.CLEARML_API_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "neuralmagic/compressed-tensors"
          path: "compressed-tensors"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: "⚙️ Install compressed-tensors dependencies"
        run: pip3 install -U pip && pip3 install setuptools compressed-tensors/
      - name: "Clean compressed-tensors directory"
        run: rm -r compressed-tensors/
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: "⚙️ Install dependencies"
        run: pip3 install .[dev,onnxruntime,torch,torchvision,transformers]
      - name: Run integration tests 
        run: |
          export CADENCE="nightly"
          pytest -s tests/sparseml/transformers -m integration
      