name: Run Nightly Tests
on:
  push:
    branches:
      - '*'
jobs:
  test-nightly-tests:
    runs-on: k8s-eng-gpu-16G-t4-32G # Should have multiple gpus enabled
    env:
      CADENCE: "nightly"
      SPARSEZOO_TEST_MODE: "true"
      CLEARML_WEB_HOST: ${{ secrets.CLEARML_WEB_HOST }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_FILES_HOST:  ${{ secrets.CLEARML_FILES_HOST }}
      CLEARML_API_SECRET_KEY:  ${{ secrets.CLEARML_API_SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: "⚙️ Install dependencies"
        run: pip3 install .[dev,onnxruntime,torch,torchvision,transformers]
      - name: Run integration tests 
        run: |
          export CADENCE="nightly"
          pytest tests/sparseml/transformers -m integeration
      